/**
 * Build the public single-page index from maintainable HTML fragments.
 *
 * Usage:
 *   node tools/build-html.mjs
 *   node tools/build-html.mjs --check
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = path.join(projectRoot, "src");
const templatePath = path.join(sourceRoot, "index.template.html");
const outputPath = path.join(projectRoot, "index.html");
const includePattern = /^([ \t]*)<!--\s*@include\s+([^\s]+)\s*-->[ \t]*$/gm;

function assertInsideSource(filePath) {
  const relative = path.relative(sourceRoot, filePath);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Include must stay inside src/: ${filePath}`);
  }
}

function indentFragment(fragment, indentation) {
  return fragment
    .replace(/\r\n/g, "\n")
    .replace(/\s+$/, "")
    .split("\n")
    .map((line) => (line.trim() ? `${indentation}${line}` : ""))
    .join("\n");
}

function expandFile(filePath, stack = []) {
  assertInsideSource(filePath);
  if (stack.includes(filePath)) {
    throw new Error(`Circular include: ${[...stack, filePath].map((item) => path.relative(sourceRoot, item)).join(" -> ")}`);
  }

  const source = fs.readFileSync(filePath, "utf8").replace(/\r\n/g, "\n");
  let output = "";
  let cursor = 0;

  for (const match of source.matchAll(includePattern)) {
    output += source.slice(cursor, match.index);
    const includePath = path.resolve(path.dirname(filePath), match[2]);
    const expanded = expandFile(includePath, [...stack, filePath]);
    output += indentFragment(expanded, match[1]);
    cursor = match.index + match[0].length;
  }

  return output + source.slice(cursor);
}

function buildHtml() {
  const expanded = expandFile(templatePath).trimEnd();
  const banner = "<!-- Generated by tools/build-html.mjs. Edit files in src/ instead of this file. -->";
  return `${expanded.replace(/^(<!doctype html>)/i, `$1\n${banner}`)}\n`;
}

const builtHtml = buildHtml();
const checkOnly = process.argv.includes("--check");

if (checkOnly) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== builtHtml) {
    process.stderr.write("index.html is out of date. Run: node tools/build-html.mjs\n");
    process.exitCode = 1;
  } else {
    process.stdout.write("index.html is up to date.\n");
  }
} else {
  fs.writeFileSync(outputPath, builtHtml, "utf8");
  process.stdout.write("Built index.html from src/.\n");
}
