/**
 * Build the public shell and generated page content from maintainable HTML fragments.
 *
 * Usage:
 *   node tools/build-html.mjs
 *   node tools/build-html.mjs --check
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = path.join(projectRoot, "src");
const includePattern = /^([ \t]*)<!--\s*@include\s+([^\s]+)\s*-->[ \t]*$/gm;
const buildTargets = [
  {
    shellTemplatePath: path.join(sourceRoot, "index.template.html"),
    appTemplatePath: path.join(sourceRoot, "app.template.html"),
    shellOutputPath: path.join(projectRoot, "index.html"),
    contentOutputPath: path.join(projectRoot, "scripts", "generated-content.js")
  },
  {
    shellTemplatePath: path.join(sourceRoot, "offensive.template.html"),
    appTemplatePath: path.join(sourceRoot, "offensive-app.template.html"),
    shellOutputPath: path.join(projectRoot, "offensive-bfm.html"),
    contentOutputPath: path.join(projectRoot, "scripts", "generated-offensive-content.js")
  }
];

function assertInsideSource(filePath) {
  const relative = path.relative(sourceRoot, filePath);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Include must stay inside src/: ${filePath}`);
  }
}

function indentFragment(fragment, indentation) {
  return fragment
    .replace(/\r\n/g, "\n")
    .replace(/\s+$/, "")
    .split("\n")
    .map((line) => (line.trim() ? `${indentation}${line}` : ""))
    .join("\n");
}

function expandFile(filePath, stack = []) {
  assertInsideSource(filePath);
  if (stack.includes(filePath)) {
    throw new Error(`Circular include: ${[...stack, filePath].map((item) => path.relative(sourceRoot, item)).join(" -> ")}`);
  }

  const source = fs.readFileSync(filePath, "utf8").replace(/\r\n/g, "\n");
  let output = "";
  let cursor = 0;

  for (const match of source.matchAll(includePattern)) {
    output += source.slice(cursor, match.index);
    const includePath = path.resolve(path.dirname(filePath), match[2]);
    const expanded = expandFile(includePath, [...stack, filePath]);
    output += indentFragment(expanded, match[1]);
    cursor = match.index + match[0].length;
  }

  return output + source.slice(cursor);
}

function buildShellHtml(templatePath) {
  const expanded = expandFile(templatePath).trimEnd();
  const banner = "<!-- Generated by tools/build-html.mjs. Edit files in src/ instead of this file. -->";
  return `${expanded.replace(/^(<!doctype html>)/i, `$1\n${banner}`)}\n`;
}

function buildContentScript(templatePath) {
  const expanded = expandFile(templatePath).trim();
  const serialized = JSON.stringify(expanded)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
  return [
    "/* Generated by tools/build-html.mjs. Edit files in src/ instead of this file. */",
    "window.BFM = window.BFM || {};",
    `window.BFM.generatedContent = ${serialized};`,
    ""
  ].join("\n");
}

const outputs = buildTargets.flatMap((target) => [
  { path: target.shellOutputPath, content: buildShellHtml(target.shellTemplatePath) },
  { path: target.contentOutputPath, content: buildContentScript(target.appTemplatePath) }
]);
const checkOnly = process.argv.includes("--check");

if (checkOnly) {
  const outdated = outputs.filter((output) => {
    const current = fs.existsSync(output.path) ? fs.readFileSync(output.path, "utf8").replace(/\r\n/g, "\n") : "";
    return current !== output.content;
  });

  if (outdated.length) {
    process.stderr.write(`${outdated.map((output) => path.relative(projectRoot, output.path)).join(", ")} is out of date. Run: node tools/build-html.mjs\n`);
    process.exitCode = 1;
  } else {
    process.stdout.write("Public page shells and generated content are up to date.\n");
  }
} else {
  for (const output of outputs) {
    fs.writeFileSync(output.path, output.content, "utf8");
  }
  process.stdout.write("Built public page shells and generated content from src/.\n");
}
